version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-022-024/sausage-store/sausage-backend:${VERSION}
    # build:
    #   context: backend
    #   dockerfile: Dockerfile 
    container_name: sausage-backend
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}" #jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_DATA_MONGODB_URI: "${SPRING_DATA_MONGODB_URI}"

      # SPRING_DATASOURCE_URL: jdbc:postgresql://rc1a-swsg2g6j6bhznvm0.mdb.yandexcloud.net:6432/std-022-024
      #SPRING_DATASOURCE_USERNAME: std-022-024
      # SPRING_DATASOURCE_PASSWORD: Testusr1234
      # SPRING_DATA_MONGODB_URI=mongodb://std-022-024:Testusr1234@rc1a-sui0a7vifhdsk9b1.mdb.yandexcloud.net:27018/report?tls=true
    # env_file:
    #   .env
    networks:
      - sausage-store
    restart: on-failure
  
  backend-report:
    build:
      context: backend-report
      dockerfile: Dockerfile
    container_name: sausage-backend-report
    environment:
      DB: "${SPRING_DATA_MONGODB_URI}"
      #"mongodb://std-022-024:Testusr1234@rc1a-sui0a7vifhdsk9b1.mdb.yandexcloud.net:27018/std-022-024?tls=true&tlsAllowInvalidCertificates=true"  #"${SPRING_DATA_MONGODB_URI}" #${REPORTS_MONGODB_URI}
    networks:
      - sausage-store
    restart: on-failure
  
  
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-022-024/sausage-store/sausage-frontend:${VERSION} 
    container_name: sausage-frontend
    ports:
      - "80:80"
    networks:
      - sausage-store
    depends_on:
      - backend
    deploy:
    restart: on-failure

networks:
  sausage-store: