stages:
  - build
  - notify

build-backend-code-job:
  stage: build  
  only:
    changes:
      - backend/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

telegram-notification-backend:
  stage: notify
  only:
    changes:
    - backend/*
  script:
    - curl -s -X POST https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage -d chat_id=-1001771539978 -d1 text="std-022-024 собрал backend [link](1$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=$CI_JOB_NAME)"
  needs:
    - build-backend-code-job