cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  JAVA_OPTS: -XX:MaxRAMPercentage=90 # для того, чтобы Maven не съел всю свободную оперативку
  SPRING_FLYWAY_ENABLED: "false"

stages:
  - build
  - notify
  - release
  - deploy

build-backend-code-job:
  stage: build  
  # only:
  #   changes:
  #     - backend/**/*
  #   variables:
  #     - $CI_COMMIT_MESSAGE =~ /send notification/
  rules: # rules и only в данных случаях взаимозаменяемы
    - changes:
      - backend/**/*
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/sausage-backend:${VERSION}"
      --build-arg VERSION=${VERSION}
      --cache=true

  artifacts:
    paths:
      - backend/target/sausage-store-${VERSION}.jar
      - ${CI_PROJECT_DIR}/.m2/ 


telegram-notification-backend:
  stage: notify
  only:
    changes:
    - backend/*
  script:
    - curl -s -X POST https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage 
      -d parse_mode=markdown
      -d chat_id=-1001771539978 
      -d text="std-022-024 собрал backend [artefact]($CI_PROJECT_URL/-/jobs/artifacts/$VERSION/download?job=build-backend-code-job)"
  needs:
    - build-backend-code-job


release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo ${VERSION}
    - crane tag $CI_REGISTRY_IMAGE/sausage-backend:${VERSION} latest


deploy-backend:
  stage: deploy
  image: docker:20.10.12-dind
  before_script:
    - apk add openssh-client bash docker-compose
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker context create --docker "host=ssh://student@std-022-24.praktikum-services.tech" remote
  script:
    - docker context use remote
    - docker rm -f sausage-backend || true
    - docker-compose -f docker-compose.yml up -d backend
  
  # before_script:
  #   - apk add openssh-client bash envsubst
  #   - eval $(ssh-agent -s)
  #   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  #   - mkdir -p ~/.ssh
  #   - chmod 700 ~/.ssh
  #   - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  #   - chmod 644 ~/.ssh/known_hosts
  # script:
  # # подставим переменные в скрипт deploy.sh и выполним его на целевом хосте, где развернем сосисочный бэкенд    
  #   - envsubst < ./backend/deploy.sh|ssh ${DEV_USER}@${DEV_HOST} 
